### ISSUE TITLE
Designs

### ISSUE THREAD

**Issue by BobrImperator** [blogic/ucentral-pwa#34]
- [x] #30 
Missing svg icons for password visiblity toggle.
- [x] #28 
Arrow icon svg 
- [x] #4 
Button states disabled and pending. 
![image](https://user-images.githubusercontent.com/15948633/119960148-f459ce00-bfa4-11eb-89a4-0018a4fb2af0.png)
![image](https://user-images.githubusercontent.com/15948633/119960192-fe7bcc80-bfa4-11eb-9c8d-dbf92ff8b9f7.png)
- [ ] Network disconnected/connected icon
https://share.goabstract.com/14416ed3-6a07-4c9e-b5e1-8ffcc1d2da23?mode=design&sha=d4e8cf429d018a8c9491f5f6e2ee266a2922f9a8
- [x] Spinner icon 
https://share.goabstract.com/d4169290-b44e-49fb-b441-a678a4d56bc9?mode=design&sha=c609991f3db28c212d5b7a820c3a81423b3681a6

**Comment by pichfl** [comment]
Button with disabled & pending states: https://codepen.io/pichfl/pen/NWpabxv

**Comment by pichfl** [comment]
Loading symbol. Can be colored by changing "currentColor" in the code or by setting `color: #f00;` on the containing element if the svg is inlined in the HTML
```
<svg height="64" viewBox="0 0 64 64" width="64" xmlns="http://www.w3.org/2000/svg"><path d="M32.024 0c17.685 0 32.022 14.337 32.022 32.023 0 5.2-1.24 10.11-3.44 14.453l-4.32-2.494a26.928 26.928 0 002.78-11.96c0-14.935-12.105-27.041-27.041-27.041-14.937 0-27.043 12.106-27.043 27.042a27.003 27.003 0 0011.013 21.783v5.944A32.011 32.011 0 01.002 32.023C.002 14.338 14.34 0 32.026 0zm26.804 49.546a32.081 32.081 0 01-2.943 3.83l-3.526-3.526a27.156 27.156 0 002.15-2.797zm-5.451 6.34a32.086 32.086 0 01-3.83 2.942l-2.494-4.32a27.167 27.167 0 002.798-2.15zm-6.9 4.719a31.916 31.916 0 01-4.464 1.85l-1.29-4.819a26.73 26.73 0 003.26-1.352zm-7.89 2.766a32.073 32.073 0 01-4.79.625V59.01a27.207 27.207 0 003.498-.457z" fill="currentColor"/></svg>
```

**Comment by marcoow** [comment]
> Network disconnected/connected icon

@BobrImperator I think that's done and we can close this?

**Comment by BobrImperator** [comment]
Yeah, I think it can be closed
